;;; llm-tool-collection-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from llm-tool-collection.el

(autoload 'llm-tool-collection-get-category "llm-tool-collection" "\
Return a list of all tool definitions in the collection part of CATEGORY.

Mapping over this list with `gptel-make-tool', `llm-make-tool', or
similar will add all tools to the respective client:

 (mapcar (apply-partially #\\='apply #\\='gptel-make-tool)
         (llm-tool-collection-get-category \"filesystem\"))

(fn CATEGORY)")
(autoload 'llm-tool-collection-get-tag "llm-tool-collection" "\
Return a list of all tool definitions in the collection tagged with TAG.

Mapping over this list with `gptel-make-tool', `llm-make-tool', or
similar will add all tools to the respective client:

 (mapcar (apply-partially #\\='apply #\\='gptel-make-tool)
         (llm-tool-collection-get-tag \\='buffer))

(fn TAG)")
(autoload 'llm-tool-collection-get-all "llm-tool-collection" "\
Return a list of all tool definitions in the collection.

Mapping over this list with `gptel-make-tool', `llm-make-tool', or
similar will add all tools to the respective client:

 (mapcar (apply-partially #\\='apply #\\='gptel-make-tool)
         (llm-tool-collection-get-all))")
(cl-pushnew (list "LLM Tools" (concat "^\\s-*(" (regexp-opt '("llm-tool-collection-deftool") t) "\\s-+\\(" lisp-mode-symbol-regexp "\\)") 2) lisp-imenu-generic-expression :test #'equal)
(defconst llm-tool-collection-font-lock-keywords '(("(\\(llm-tool-collection-deftool\\)\\_>[ 	'(]*\\(\\(?:\\sw\\|\\s_\\)+\\)?" (1 'font-lock-keyword-face) (2 'font-lock-function-name-face nil t))))
(font-lock-add-keywords 'emacs-lisp-mode llm-tool-collection-font-lock-keywords)
(register-definition-prefixes "llm-tool-collection" '("llm-tool-collection-"))

;;; End of scraped data

(provide 'llm-tool-collection-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; llm-tool-collection-autoloads.el ends here
