#!/bin/bash
set -eu -o pipefail

focused_win_id() {
	xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME
}

i3-msg mark focused_container
window_id=$(wmctrl -l | tr -s ' ' | cut -d' ' -f1,4- | rofi -normal-window -dmenu -i | cut -d' ' -f1)
i3-msg [id="$window_id"] move window to mark focused_container
i3-msg mark
i3-msg [id="$window_id"] focus
