#!/bin/bash
set -eu -o pipefail

focused_win_id() {
	xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME
}

id=$(focused_win_id)
i3-msg mark focused_container
i3-msg [workspace="__focused__"] move window to mark focused_container
i3-msg mark
i3-msg [id="$window_id"] focus
