#+TITLE: A Coder's Plover Dictionary
#+PROPERTY: header-args :tangle user.json

* about this config
I am a heavy user of emacs, vim, and the linux command line. When it comes to coding, the main challenge I have experienced with Plover is the automatic spacing and capitalization. While automatic spacing and capitalization is a big part of what makes stenography so efficient when typing natural language, it can wreak havoc in other contexts. For example, the unexpected insertion of spaces can interfere with the composition of normal mode commands in vim (e.g. "d3j" to delete the current line and the 3 lines below it). For this reason, I have overridden the default fingerspelling behavior to always attach the new letter/number to the end of the current word.

Another challenge is that there is no auto-repeat when holding down keys on a steno machine. This prevents you from holding down "j" and "k" to scroll up and down in vim, for example. You might be surprised how often you use this functionality, even if you are a seasoned vimmer. While I'm still working on it, I'm attempting to overcome this issue by using a combination of =relativenumber= and numeric arguments before j/k.
* start dictionary
#+BEGIN_SRC js
{
#+END_SRC
* bioinformatics
#+BEGIN_SRC js
"PWEUS": "ABySS",
"ARBGS": "arcs",
"A*RBGS": "arks",
"KOPB/TEUG": "contig",
"KOPB/TEUGS": "contigs",
"TKEUFT": "dist",
"EPL": "emc",
"TPHAFRPB": "Inanc",
"PRAG": "pragma",
"KWAFT": "quast",
"REPB/AEU": "Rene",
"SHAUPB": "Shaun",
"SEUT/KA": "Sitka",
"TEUG/PHEUPBT": "Tigmint",
"AOUPB/TEUG": "unitig",
"AOUPB/TEUGS": "unitigs",
#+END_SRC

* brackets
#+BEGIN_SRC js
"HR-RPB": "{^}({^}",
"PW-RPB": "{^}[{^}",
"TK-RPB": "{^}\\{{^}",
"S-RPB":  "{^}<",
"S-RPBS":  "<<",
"PWR-FR": "{^})",
"PWR-PB": "{^}]",
"PWR-LG": "{^}\\}",
"PWR-TS": "{^}>",
"PWR-S": "{^}>",
#+END_SRC
* C/C++
#+BEGIN_SRC js
"KHR-PBS": "{^}::{^}",
"KRER": "cerr",
"KROUT": "cout",
"KOPBTS": "const",
"ST-D": "std{^}",
"STRUBGT": "struct",
"TAOEUP/TKEF": "typedef",
"TAOEUP/TPHAEUPL": "typename",
#+END_SRC
* command-line
** shell commands
#+BEGIN_SRC js
"POEUP": "{&../}",
"POEU": "{&./}",
"OEUP": "{&./}",
"TKR-": "cd",
"KR-D": "cd",
"KR-P": "cp",
"SKWRA*EUFPB": "json",
"HR-S": "ls",
"HR-PB": "ln",
"PH-D": "mkdir",
"PH-F": "mv",
"O*RG": "org",
"PW-D": "pwd",
"R-PL": "rm",
"R-D": "rmdir",
"SH": "ssh",
"TPHUBGS": "tmux",
"KPARGS": "xargs",
#+END_SRC
** command-line switches
#+BEGIN_SRC js
"TK-RB": "{MODE:RESET}{& --}",
"A-RBG": "{MODE:RESET}{& -a}",
"PW-RBG": "{MODE:RESET}{& -b}",
"KR-RBG": "{MODE:RESET}{& -c}",
"TK-RBG": "{MODE:RESET}{& -d}",
"-ERBG": "{MODE:RESET}{& -e}",
"TP-RBG": "{MODE:RESET}{& -f}",
"TKPW-RBG": "{MODE:RESET}{& -g}",
"H-RBG": "{MODE:RESET}{& -h}",
"-EUFP": "{MODE:RESET}{& -i}",
"SKWR-RBG": "{MODE:RESET}{& -j}",
"K-RBG": "{MODE:RESET}{& -k}",
"HR-RBG": "{MODE:RESET}{& -l}",
"PH-RBG": "{MODE:RESET}{& -m}",
"TPH-RBG": "{MODE:RESET}{& -n}",
"O-RBG": "{MODE:RESET}{& -o}",
"P-RBG": "{MODE:RESET}{& -p}",
"KW-RBG": "{MODE:RESET}{& -q}",
"R-RBG": "{MODE:RESET}{& -r}",
"S-RBG": "{MODE:RESET}{& -s}",
"T-RBG": "{MODE:RESET}{& -t}",
"-URBG": "{MODE:RESET}{& -u}",
"SR-RBG": "{MODE:RESET}{& -v}",
"W-RBG": "{MODE:RESET}{& -w}",
"KP-RBG": "{MODE:RESET}{& -x}",
"KPR-RBG": "{MODE:RESET}{& -y}",
"STKPW-RBG": "{MODE:RESET}{& -z}",
"A-RPBG": "{MODE:RESET}{& -A}",
"PW-RPBG": "{MODE:RESET}{& -B}",
"KR-RPBG": "{MODE:RESET}{& -C}",
"TK-RPBG": "{MODE:RESET}{& -D}",
"-EF": "{MODE:RESET}{& -E}",
"KPWR-E": "{MODE:RESET}{& -E}",
"TP-RPBG": "{MODE:RESET}{& -F}",
"TKPW-RPBG": "{MODE:RESET}{& -G}",
"H-RPBG": "{MODE:RESET}{& -H}",
"-EUFPL": "{MODE:RESET}{& -I}",
"KPWR-EU": "{MODE:RESET}{& -I}",
"SKWR-RPBG": "{MODE:RESET}{& -J}",
"K-RPBG": "{MODE:RESET}{& -K}",
"HR-RPBG": "{MODE:RESET}{& -L}",
"TPH-RPBG": "{MODE:RESET}{& -M}",
"TPH-RPBG": "{MODE:RESET}{& -N}",
"O-RPBG": "{MODE:RESET}{& -O}",
"P-RPBG": "{MODE:RESET}{& -P}",
"KW-RPBG": "{MODE:RESET}{& -Q}",
"R-RPBG": "{MODE:RESET}{& -R}",
"S-RPBG": "{MODE:RESET}{& -S}",
"T-RPBG": "{MODE:RESET}{& -T}",
"-URPBG": "{MODE:RESET}{& -U}",
"KPWR-U": "{MODE:RESET}{& -U}",
"SR-RPBG": "{MODE:RESET}{& -V}",
"W-RPBG": "{MODE:RESET}{& -W}",
"KP-RPBG": "{MODE:RESET}{& -X}",
"KPR-RPBG": "{MODE:RESET}{& -Y}",
"STKPW-RPBG": "{MODE:RESET}{& -Z}",
#+END_SRC
* function keys
To type a function key (e.g. F1), hold down -PL and fingerspell the number with the left hand. The mnemonic for -PL is that it is the mirror image for fingerspelling "F" with the left hand.
#+BEGIN_SRC js
"178": "{#F1}",
"278": "{#F2}",
"378": "{#F3}",
"478": "{#F4}",
"578": "{#F5}",
"678": "{#F6}",
"778": "{#F7}",
"878": "{#F8}",
"978": "{#F9}",
"1078": "{#F10}",
"1278": "{#F12}",
#+END_SRC
* modifier keys (alt/control/shift/win)
** alt
#+BEGIN_SRC js
"KHR*FPB": "{#alt(shift(colon))}",
"P*FP": "{#alt(period)}",
"S*FP": "{#alt(space)}",
"SH*P": "{#alt(space)}",
"HO*EU": "{#alt(slash)}",
"O*EUF": "{#alt(slash)}",
"T*FB": "{#alt(tab)}",
"TH*B": "{#alt(tab)}",
"A*F": "{#alt(a)}",
"PW*F": "{#alt(b)}",
"KR*F": "{#alt(c)}",
"TK*F": "{#alt(d)}",
"*EF": "{#alt(e)}",
"H*E": "{#alt(e)}",
"TP*F": "{#alt(f)}",
"TKPW*F": "{#alt(g)}",
"H*F": "{#alt(h)}",
"*EUF": "{#alt(i)}",
"H*EU": "{#alt(i)}",
"SKWR*F": "{#alt(j)}",
"K*F": "{#alt(k)}",
"HR*F": "{#alt(l)}",
"PH*F": "{#alt(m)}",
"TPH*F": "{#alt(n)}",
"O*F": "{#alt(o)}",
"P*F": "{#alt(p)}",
"KW*F": "{#alt(q)}",
"R*F": "{#alt(r)}",
"S*F": "{#alt(s)}",
"T*F": "{#alt(t)}",
"*UF": "{#alt(u)}",
"W*U": "{#alt(u)}",
"SR*F": "{#alt(v)}",
"W*F": "{#alt(w)}",
"KP*F": "{#alt(x)}",
"KWR*F": "{#alt(y)}",
"STKPW*F": "{#alt(z)}",
#+END_SRC
** control
#+BEGIN_SRC js
"HR*RPB": "{#control(parenleft)}",
"PW*RPB": "{#control(bracketleft)}",
"TK*RPB": "{#control(braceleft)}",
"PWR*FR": "{#control(parenright)}",
"PWR*PB": "{#control(bracketright)}",
"PWR*LG": "{#control(braceright)}",
"KHR-R": "{#control(left)}",
"KHR-G": "{#control(right)}",
"KHR-P": "{#control(up)}",
"KHR-B": "{#control(down)}",
"R*EUPBS": "{#control(insert)}",
"R*T": "{#control(shift(plus))}",
"R*S": "{#control(minus)}",
"RO*EU": "{#control(slash)}",
"O*EUR": "{#control(slash)}",
"S*RP": "{#control(space)}",
"T*RB": "{#control(tab)}",
"TR*B": "{#control(tab)}",
"A*R": "{#control(a)}",
"PW*R": "{#control(b)}",
"KR*R": "{#control(c)}",
"TK*R": "{#control(d)}",
"R*E": "{#control(e)}",
"TP*R": "{#control(f)}",
"TKPW*R": "{#control(g)}",
"H*R": "{#control(h)}",
"*EUR": "{#control(i)}",
"R*EU": "{#control(i)}",
"SKWR*R": "{#control(j)}",
"K*R": "{#control(k)}",
"HR*R": "{#control(l)}",
"PH*R": "{#control(m)}",
"TPH*R": "{#control(n)}",
"O*R": "{#control(o)}",
"P*R": "{#control(p)}",
"KW*R": "{#control(q)}",
"R*R": "{#control(r)}",
"S*R": "{#control(s)}",
"T*R": "{#control(t)}",
"*UR": "{#control(u)}",
"R*U": "{#control(u)}",
"SR*R": "{#control(v)}",
"W*R": "{#control(w)}",
"KP*R": "{#control(x)}",
"KWR*R": "{#control(y)}",
"STKPW*R": "{#control(z)}",
#+END_SRC
** shift
#+BEGIN_SRC js
"SH*EUPBS": "{#shift(insert)}",
"SH*P": "{#shift(up)}",
"SH*B": "{#shift(down)}",
"SH*R": "{#shift(left)}",
"SH*G": "{#shift(right)}",
"SH*RB": "{#shift(control(left))}",
"SH*BG": "{#shift(control(right))}",
#+END_SRC
** win
#+BEGIN_SRC js
"*PB": "{#windows}",
"R*RPB": "{#windows(return)}",
"PWR*R": "{#windows(return)}",
"P*LG": "{#windows(up)}",
"K*LG": "{#windows(left)}",
"W*LG": "{#windows(down)}",
"R*LG": "{#windows(right)}",
"A*PB": "{#windows(a)}",
"PW*PB": "{#windows(b)}",
"KR*PB": "{#windows(c)}",
"TK*PB": "{#windows(d)}",
"*EPB": "{#windows(e)}",
"TP*PB": "{#windows(f)}",
"TKPW*PB": "{#windows(g)}",
"H*PB": "{#windows(h)}",
"*EUPB": "{#windows(i)}",
"SKWR*PB": "{#windows(j)}",
"K*PB": "{#windows(k)}",
"HR*PB": "{#windows(l)}",
"PH*PB": "{#windows(m)}",
"TPH*PB": "{#windows(n)}",
"O*PB": "{#windows(o)}",
"P*PB": "{#windows(p)}",
"KW*PB": "{#windows(q)}",
"R*PB": "{#windows(r)}",
"S*PB": "{#windows(s)}",
"T*PB": "{#windows(t)}",
"*UPB": "{#windows(u)}",
"SR*PB": "{#windows(v)}",
"W*PB": "{#windows(w)}",
"KP*PB": "{#windows(x)}",
"KWR*PB": "{#windows(y)}",
"STKPW*PB": "{#windows(z)}",
#+END_SRC
** win+shift
Same as the Windows key chords, but with the S key appended at the end.
#+BEGIN_SRC js
"A*PBS": "{#windows(shift(a))}",
"PW*PBS": "{#windows(shift(b))}",
"KR*PBS": "{#windows(shift(c))}",
"TK*PBS": "{#windows(shift(d))}",
"*EPBS": "{#windows(shift(e))}",
"TP*PBS": "{#windows(shift(f))}",
"TKPW*PBS": "{#windows(shift(g))}",
"H*PBS": "{#windows(shift(h))}",
"*EUPBS": "{#windows(shift(i))}",
"SKWR*PBS": "{#windows(shift(j))}",
"K*PBS": "{#windows(shift(k))}",
"HR*PBS": "{#windows(shift(l))}",
"PH*PBS": "{#windows(shift(m))}",
"TPH*PBS": "{#windows(shift(n))}",
"O*PBS": "{#windows(shift(o))}",
"P*PBS": "{#windows(shift(p))}",
"KW*PBS": "{#windows(shift(q))}",
"R*PBS": "{#windows(shift(r))}",
"S*PBS": "{#windows(shift(s))}",
"T*PBS": "{#windows(shift(t))}",
"*UPBS": "{#windows(shift(u))}",
"SR*PBS": "{#windows(shift(v))}",
"W*PBS": "{#windows(shift(w))}",
"KP*PBS": "{#windows(shift(x))}",
"KWR*PBS": "{#windows(shift(y))}",
"STKPW*PBS": "{#windows(shift(z))}",
#+END_SRC

* escape key

Pressing the number bar on its own triggers the Esc key. I love this mapping because the location is similar to the Escape key on a regular keyboard but is much easier to reach.

At the same time, pressing the number bar on its own also resets plover to its default mode.

#+BEGIN_SRC js
"#": "{#escape}{MODE:RESET}{MODE:LOWER}",
"#*": "{#escape}",
#+END_SRC
* fingerspelling
In this section, we override the default behavior of fingerspelling to attach all fingerspelled letters/symbols/numbers to the end of the current word. This prevents Plover's automatic spacing from interfering with the typing of normal mode commands in vim.
** letters
#+BEGIN_SRC js
"A*": "{^}a",
"PW*": "{^}b",
"KR*": "{^}c",
"TK*": "{^}d",
"*E": "{^}e",
"TP*": "{^}f",
"TKPW*": "{^}g",
"H*": "{^}h",
"*EU": "{^}i",
"SKWR*": "{^}j",
"K*": "{^}k",
"HR*": "{^}l",
"PH*": "{^}m",
"TPH*": "{^}n",
"O*": "{^}o",
"P*": "{^}p",
"KW*": "{^}q",
"R*": "{^}r",
"S*": "{^}s",
"T*": "{^}t",
"*U": "{^}u",
"SR*": "{^}v",
"W*": "{^}w",
"KP*": "{^}x",
"KWR*": "{^}y",
"STKPW*": "{^}z",
"A*P": "{MODE:RESET}{^}A",
"PW*P": "{MODE:RESET}{^}B",
"KR*P": "{MODE:RESET}{^}C",
"TK*P": "{MODE:RESET}{^}D",
"*EP": "{MODE:RESET}{^}E",
"P*E": "{MODE:RESET}{^}E",
"TP*P": "{MODE:RESET}{^}F",
"TKPW*P": "{MODE:RESET}{^}G",
"H*P": "{MODE:RESET}{^}H",
"*EUP": "{MODE:RESET}{^}I",
"P*EU": "{MODE:RESET}{^}I",
"SKWR*P": "{MODE:RESET}{^}J",
"K*P": "{MODE:RESET}{^}K",
"HR*P": "{MODE:RESET}{^}L",
"PH*P": "{MODE:RESET}{^}M",
"TPH*P": "{MODE:RESET}{^}N",
"O*P": "{MODE:RESET}{^}O",
"P*P": "{MODE:RESET}{^}P",
"KW*P": "{MODE:RESET}{^}Q",
"R*P": "{MODE:RESET}{^}R",
"S*P": "{MODE:RESET}{^}S",
"T*P": "{MODE:RESET}{^}T",
"*UP": "{MODE:RESET}{^}U",
"P*U": "{MODE:RESET}{^}U",
"SR*P": "{MODE:RESET}{^}V",
"W*P": "{MODE:RESET}{^}W",
"KP*P": "{MODE:RESET}{^}X",
"KWR*P": "{MODE:RESET}{^}Y",
"STKPW*P": "{MODE:RESET}{^}Z",
#+END_SRC
** numbers
#+BEGIN_SRC js
"0": "{^}0",
"1": "{^}1",
"2": "{^}2",
"3": "{^}3",
"4": "{^}4",
"5": "{^}5",
"6": "{^}6",
"7": "{^}7",
"8": "{^}8",
"9": "{^}9",
"10-EU": "{^}01",
"20-EU": "{^}02",
"30-EU": "{^}03",
"40-EU": "{^}04",
"50-EU": "{^}05",
"60-EU": "{^}06",
"70-EU": "{^}07",
"80-EU": "{^}08",
"90-EU": "{^}09",
"01-EU": "{^}10",
"12": "{^}12",
"13": "{^}13",
"14": "{^}14",
"15": "{^}15",
"16": "{^}16",
"17": "{^}17",
"18": "{^}18",
"19": "{^}19",
"02-EU": "{^}20",
"12-EU": "{^}21",
"23": "{^}23",
"24": "{^}24",
"25": "{^}25",
"26": "{^}26",
"27": "{^}27",
"28": "{^}28",
"29": "{^}29",
"03-EU": "{^}30",
"13-EU": "{^}31",
"23-EU": "{^}32",
"34": "{^}34",
"35": "{^}35",
"36": "{^}36",
"37": "{^}37",
"38": "{^}38",
"39": "{^}39",
#+END_SRC
** symbol chars (e.g. !, @, #)
Assign these to the number keys, similar to a normal keyboard, using the star key ("*") as the modifier.
#+BEGIN_SRC js
"0*": "{^})",
"1*": "{^}!",
"2*": "{^}@",
"3*": "{^}#",
"4*": "{^}$",
"5*": "{^}%",
"*6": "{^}^",
"*7": "{^}&",
"*8": "{^}*",
"*9": "{^}(",
#+END_SRC
** digrams

I find the ability to fingerspell digrams (two-letter combinations) to be very handy. For example, I have used various vim plugins for Firefox/Chrome (e.g. Vimperator, Vimium, VimFX, tridactyl) that allow keyboard navigation of hyperlinks by labeling the links with two-letter "hints".

The idea behind these chords is to fingerspell the first letter with the left hand as usual, and to use the right hand to fingerspell the second letter. The chords for fingerspelling the right hand are the mirror image of the chords for the left hand. For example, the right hand chord for "m" is -FP. Finally, all digram chords end with the Z key.

#+BEGIN_SRC js
"A-PBZ": "{^}ab",
"A-RGZ": "{^}ac",
"A-LGZ": "{^}ad",
"A-EZ": "{^}ae",
"A-PLZ": "{^}af",
"A-PBLGZ": "{^}ag",
"A-FZ": "{^}ah",
"A-EUZ": "{^}ai",
"A-RBGSZ": "{^}aj",
"A-GZ": "{^}ak",
"A-FRZ": "{^}al",
"A-FPZ": "{^}am",
"A-FPLZ": "{^}an",
"AO-Z": "{^}ao",
"A-PZ": "{^}ap",
"A-BGZ": "{^}aq",
"A-RZ": "{^}ar",
"A-SZ": "{^}as",
"A-LZ": "{^}at",
"A-UZ": "{^}au",
"A-RSZ": "{^}av",
"A-BZ": "{^}aw",
"A-PGZ": "{^}ax",
"A-RBGZ": "{^}ay",
"A-PBLGSZ": "{^}az",
"PWA-Z": "{^}ba",
"PW-PBZ": "{^}bb",
"PW-RGZ": "{^}bc",
"PW-LGZ": "{^}bd",
"PW-EZ": "{^}be",
"PW-PLZ": "{^}bf",
"PW-PBLGZ": "{^}bg",
"PW-FZ": "{^}bh",
"PW-EUZ": "{^}bi",
"PW-RBGSZ": "{^}bj",
"PW-GZ": "{^}bk",
"PW-FRZ": "{^}bl",
"PW-FPZ": "{^}bm",
"PW-FPLZ": "{^}bn",
"PWO-Z": "{^}bo",
"PW-PZ": "{^}bp",
"PW-BGZ": "{^}bq",
"PW-RZ": "{^}br",
"PW-SZ": "{^}bs",
"PW-LZ": "{^}bt",
"PW-UZ": "{^}bu",
"PW-RSZ": "{^}bv",
"PW-BZ": "{^}bw",
"PW-PGZ": "{^}bx",
"PW-RBGZ": "{^}by",
"PW-PBLGSZ": "{^}bz",
"KRA-Z": "{^}ca",
"KR-PBZ": "{^}cb",
"KR-RGZ": "{^}cc",
"KR-LGZ": "{^}cd",
"KR-EZ": "{^}ce",
"KR-PLZ": "{^}cf",
"KR-PBLGZ": "{^}cg",
"KR-FZ": "{^}ch",
"KR-EUZ": "{^}ci",
"KR-RBGSZ": "{^}cj",
"KR-GZ": "{^}ck",
"KR-FRZ": "{^}cl",
"KR-FPZ": "{^}cm",
"KR-FPLZ": "{^}cn",
"KRO-Z": "{^}co",
"KR-PZ": "{^}cp",
"KR-BGZ": "{^}cq",
"KR-RZ": "{^}cr",
"KR-SZ": "{^}cs",
"KR-LZ": "{^}ct",
"KR-UZ": "{^}cu",
"KR-RSZ": "{^}cv",
"KR-BZ": "{^}cw",
"KR-PGZ": "{^}cx",
"KR-RBGZ": "{^}cy",
"KR-PBLGSZ": "{^}cz",
"TKA-Z": "{^}da",
"TK-PBZ": "{^}db",
"TK-RGZ": "{^}dc",
"TK-LGZ": "{^}dd",
"TK-EZ": "{^}de",
"TK-PLZ": "{^}df",
"TK-PBLGZ": "{^}dg",
"TK-FZ": "{^}dh",
"TK-EUZ": "{^}di",
"TK-RBGSZ": "{^}dj",
"TK-GZ": "{^}dk",
"TK-FRZ": "{^}dl",
"TK-FPZ": "{^}dm",
"TK-FPLZ": "{^}dn",
"TKO-Z": "{^}do",
"TK-PZ": "{^}dp",
"TK-BGZ": "{^}dq",
"TK-RZ": "{^}dr",
"TK-SZ": "{^}ds",
"TK-LZ": "{^}dt",
"TK-UZ": "{^}du",
"TK-RSZ": "{^}dv",
"TK-BZ": "{^}dw",
"TK-PGZ": "{^}dx",
"TK-RBGZ": "{^}dy",
"TK-PBLGSZ": "{^}dz",
"EPBZ": "{^}eb",
"ERGZ": "{^}ec",
"ELGZ": "{^}ed",
"EPLZ": "{^}ef",
"EPBLGZ": "{^}eg",
"EFZ": "{^}eh",
"EEUZ": "{^}ei",
"ERBGSZ": "{^}ej",
"EGZ": "{^}ek",
"EFRZ": "{^}el",
"EFPZ": "{^}em",
"EFPLZ": "{^}en",
"EPZ": "{^}ep",
"EBGZ": "{^}eq",
"ERZ": "{^}er",
"ESZ": "{^}es",
"ELZ": "{^}et",
"EUZ": "{^}eu",
"ERSZ": "{^}ev",
"EBZ": "{^}ew",
"EPGZ": "{^}ex",
"ERBGZ": "{^}ey",
"EPBLGSZ": "{^}ez",
"TPA-Z": "{^}fa",
"TP-PBZ": "{^}fb",
"TP-RGZ": "{^}fc",
"TP-LGZ": "{^}fd",
"TP-EZ": "{^}fe",
"TP-PLZ": "{^}ff",
"TP-PBLGZ": "{^}fg",
"TP-FZ": "{^}fh",
"TP-EUZ": "{^}fi",
"TP-RBGSZ": "{^}fj",
"TP-GZ": "{^}fk",
"TP-FRZ": "{^}fl",
"TP-FPZ": "{^}fm",
"TP-FPLZ": "{^}fn",
"TPO-Z": "{^}fo",
"TP-PZ": "{^}fp",
"TP-BGZ": "{^}fq",
"TP-RZ": "{^}fr",
"TP-SZ": "{^}fs",
"TP-LZ": "{^}ft",
"TP-UZ": "{^}fu",
"TP-RSZ": "{^}fv",
"TP-BZ": "{^}fw",
"TP-PGZ": "{^}fx",
"TP-RBGZ": "{^}fy",
"TP-PBLGSZ": "{^}fz",
"TKPWA-Z": "{^}ga",
"TKPW-PBZ": "{^}gb",
"TKPW-RGZ": "{^}gc",
"TKPW-LGZ": "{^}gd",
"TKPW-EZ": "{^}ge",
"TKPW-PLZ": "{^}gf",
"TKPW-PBLGZ": "{^}gg",
"TKPW-FZ": "{^}gh",
"TKPW-EUZ": "{^}gi",
"TKPW-RBGSZ": "{^}gj",
"TKPW-GZ": "{^}gk",
"TKPW-FRZ": "{^}gl",
"TKPW-FPZ": "{^}gm",
"TKPW-FPLZ": "{^}gn",
"TKPWO-Z": "{^}go",
"TKPW-PZ": "{^}gp",
"TKPW-BGZ": "{^}gq",
"TKPW-RZ": "{^}gr",
"TKPW-SZ": "{^}gs",
"TKPW-LZ": "{^}gt",
"TKPW-UZ": "{^}gu",
"TKPW-RSZ": "{^}gv",
"TKPW-BZ": "{^}gw",
"TKPW-PGZ": "{^}gx",
"TKPW-RBGZ": "{^}gy",
"TKPW-PBLGSZ": "{^}gz",
"HA-Z": "{^}ha",
"H-PBZ": "{^}hb",
"H-RGZ": "{^}hc",
"H-LGZ": "{^}hd",
"H-EZ": "{^}he",
"H-PLZ": "{^}hf",
"H-PBLGZ": "{^}hg",
"H-FZ": "{^}hh",
"H-EUZ": "{^}hi",
"H-RBGSZ": "{^}hj",
"H-GZ": "{^}hk",
"H-FRZ": "{^}hl",
"H-FPZ": "{^}hm",
"H-FPLZ": "{^}hn",
"HO-Z": "{^}ho",
"H-PZ": "{^}hp",
"H-BGZ": "{^}hq",
"H-RZ": "{^}hr",
"H-SZ": "{^}hs",
"H-LZ": "{^}ht",
"H-UZ": "{^}hu",
"H-RSZ": "{^}hv",
"H-BZ": "{^}hw",
"H-PGZ": "{^}hx",
"H-RBGZ": "{^}hy",
"H-PBLGSZ": "{^}hz",
"EUPBZ": "{^}ib",
"EURGZ": "{^}ic",
"EULGZ": "{^}id",
"EUPLZ": "{^}if",
"EUPBLGZ": "{^}ig",
"EUFZ": "{^}ih",
"EUEUZ": "{^}ii",
"EURBGSZ": "{^}ij",
"EUGZ": "{^}ik",
"EUFRZ": "{^}il",
"EUFPZ": "{^}im",
"EUFPLZ": "{^}in",
"EUPZ": "{^}ip",
"EUBGZ": "{^}iq",
"EURZ": "{^}ir",
"EUSZ": "{^}is",
"EULZ": "{^}it",
"EUUZ": "{^}iu",
"EURSZ": "{^}iv",
"EUBZ": "{^}iw",
"EUPGZ": "{^}ix",
"EURBGZ": "{^}iy",
"EUPBLGSZ": "{^}iz",
"SKWRA-Z": "{^}ja",
"SKWR-PBZ": "{^}jb",
"SKWR-RGZ": "{^}jc",
"SKWR-LGZ": "{^}jd",
"SKWR-EZ": "{^}je",
"SKWR-PLZ": "{^}jf",
"SKWR-PBLGZ": "{^}jg",
"SKWR-FZ": "{^}jh",
"SKWR-EUZ": "{^}ji",
"SKWR-RBGSZ": "{^}jj",
"SKWR-GZ": "{^}jk",
"SKWR-FRZ": "{^}jl",
"SKWR-FPZ": "{^}jm",
"SKWR-FPLZ": "{^}jn",
"SKWRO-Z": "{^}jo",
"SKWR-PZ": "{^}jp",
"SKWR-BGZ": "{^}jq",
"SKWR-RZ": "{^}jr",
"SKWR-SZ": "{^}js",
"SKWR-LZ": "{^}jt",
"SKWR-UZ": "{^}ju",
"SKWR-RSZ": "{^}jv",
"SKWR-BZ": "{^}jw",
"SKWR-PGZ": "{^}jx",
"SKWR-RBGZ": "{^}jy",
"SKWR-PBLGSZ": "{^}jz",
"KA-Z": "{^}ka",
"K-PBZ": "{^}kb",
"K-RGZ": "{^}kc",
"K-LGZ": "{^}kd",
"K-EZ": "{^}ke",
"K-PLZ": "{^}kf",
"K-PBLGZ": "{^}kg",
"K-FZ": "{^}kh",
"K-EUZ": "{^}ki",
"K-RBGSZ": "{^}kj",
"K-GZ": "{^}kk",
"K-FRZ": "{^}kl",
"K-FPZ": "{^}km",
"K-FPLZ": "{^}kn",
"KO-Z": "{^}ko",
"K-PZ": "{^}kp",
"K-BGZ": "{^}kq",
"K-RZ": "{^}kr",
"K-SZ": "{^}ks",
"K-LZ": "{^}kt",
"K-UZ": "{^}ku",
"K-RSZ": "{^}kv",
"K-BZ": "{^}kw",
"K-PGZ": "{^}kx",
"K-RBGZ": "{^}ky",
"K-PBLGSZ": "{^}kz",
"HRA-Z": "{^}la",
"HR-PBZ": "{^}lb",
"HR-RGZ": "{^}lc",
"HR-LGZ": "{^}ld",
"HR-EZ": "{^}le",
"HR-PLZ": "{^}lf",
"HR-PBLGZ": "{^}lg",
"HR-FZ": "{^}lh",
"HR-EUZ": "{^}li",
"HR-RBGSZ": "{^}lj",
"HR-GZ": "{^}lk",
"HR-FRZ": "{^}ll",
"HR-FPZ": "{^}lm",
"HR-FPLZ": "{^}ln",
"HRO-Z": "{^}lo",
"HR-PZ": "{^}lp",
"HR-BGZ": "{^}lq",
"HR-RZ": "{^}lr",
"HR-SZ": "{^}ls",
"HR-LZ": "{^}lt",
"HR-UZ": "{^}lu",
"HR-RSZ": "{^}lv",
"HR-BZ": "{^}lw",
"HR-PGZ": "{^}lx",
"HR-RBGZ": "{^}ly",
"HR-PBLGSZ": "{^}lz",
"PHA-Z": "{^}ma",
"PH-PBZ": "{^}mb",
"PH-RGZ": "{^}mc",
"PH-LGZ": "{^}md",
"PH-EZ": "{^}me",
"PH-PLZ": "{^}mf",
"PH-PBLGZ": "{^}mg",
"PH-FZ": "{^}mh",
"PH-EUZ": "{^}mi",
"PH-RBGSZ": "{^}mj",
"PH-GZ": "{^}mk",
"PH-FRZ": "{^}ml",
"PH-FPZ": "{^}mm",
"PH-FPLZ": "{^}mn",
"PHO-Z": "{^}mo",
"PH-PZ": "{^}mp",
"PH-BGZ": "{^}mq",
"PH-RZ": "{^}mr",
"PH-SZ": "{^}ms",
"PH-LZ": "{^}mt",
"PH-UZ": "{^}mu",
"PH-RSZ": "{^}mv",
"PH-BZ": "{^}mw",
"PH-PGZ": "{^}mx",
"PH-RBGZ": "{^}my",
"PH-PBLGSZ": "{^}mz",
"TPHA-Z": "{^}na",
"TPH-PBZ": "{^}nb",
"TPH-RGZ": "{^}nc",
"TPH-LGZ": "{^}nd",
"TPH-EZ": "{^}ne",
"TPH-PLZ": "{^}nf",
"TPH-PBLGZ": "{^}ng",
"TPH-FZ": "{^}nh",
"TPH-EUZ": "{^}ni",
"TPH-RBGSZ": "{^}nj",
"TPH-GZ": "{^}nk",
"TPH-FRZ": "{^}nl",
"TPH-FPZ": "{^}nm",
"TPH-FPLZ": "{^}nn",
"TPHO-Z": "{^}no",
"TPH-PZ": "{^}np",
"TPH-BGZ": "{^}nq",
"TPH-RZ": "{^}nr",
"TPH-SZ": "{^}ns",
"TPH-LZ": "{^}nt",
"TPH-UZ": "{^}nu",
"TPH-RSZ": "{^}nv",
"TPH-BZ": "{^}nw",
"TPH-PGZ": "{^}nx",
"TPH-RBGZ": "{^}ny",
"TPH-PBLGSZ": "{^}nz",
"O-PBZ": "{^}ob",
"O-RGZ": "{^}oc",
"O-LGZ": "{^}od",
"O-EZ": "{^}oe",
"O-PLZ": "{^}of",
"O-PBLGZ": "{^}og",
"O-FZ": "{^}oh",
"O-EUZ": "{^}oi",
"O-RBGSZ": "{^}oj",
"O-GZ": "{^}ok",
"O-FRZ": "{^}ol",
"O-FPZ": "{^}om",
"O-FPLZ": "{^}on",
"O-PZ": "{^}op",
"O-BGZ": "{^}oq",
"O-RZ": "{^}or",
"O-SZ": "{^}os",
"O-LZ": "{^}ot",
"O-UZ": "{^}ou",
"O-RSZ": "{^}ov",
"O-BZ": "{^}ow",
"O-PGZ": "{^}ox",
"O-RBGZ": "{^}oy",
"O-PBLGSZ": "{^}oz",
"PA-Z": "{^}pa",
"P-PBZ": "{^}pb",
"P-RGZ": "{^}pc",
"P-LGZ": "{^}pd",
"P-EZ": "{^}pe",
"P-PLZ": "{^}pf",
"P-PBLGZ": "{^}pg",
"P-FZ": "{^}ph",
"P-EUZ": "{^}pi",
"P-RBGSZ": "{^}pj",
"P-GZ": "{^}pk",
"P-FRZ": "{^}pl",
"P-FPZ": "{^}pm",
"P-FPLZ": "{^}pn",
"PO-Z": "{^}po",
"P-PZ": "{^}pp",
"P-BGZ": "{^}pq",
"P-RZ": "{^}pr",
"P-SZ": "{^}ps",
"P-LZ": "{^}pt",
"P-UZ": "{^}pu",
"P-RSZ": "{^}pv",
"P-BZ": "{^}pw",
"P-PGZ": "{^}px",
"P-RBGZ": "{^}py",
"P-PBLGSZ": "{^}pz",
"KWA-Z": "{^}qa",
"KW-PBZ": "{^}qb",
"KW-RGZ": "{^}qc",
"KW-LGZ": "{^}qd",
"KW-EZ": "{^}qe",
"KW-PLZ": "{^}qf",
"KW-PBLGZ": "{^}qg",
"KW-FZ": "{^}qh",
"KW-EUZ": "{^}qi",
"KW-RBGSZ": "{^}qj",
"KW-GZ": "{^}qk",
"KW-FRZ": "{^}ql",
"KW-FPZ": "{^}qm",
"KW-FPLZ": "{^}qn",
"KWO-Z": "{^}qo",
"KW-PZ": "{^}qp",
"KW-BGZ": "{^}qq",
"KW-RZ": "{^}qr",
"KW-SZ": "{^}qs",
"KW-LZ": "{^}qt",
"KW-UZ": "{^}qu",
"KW-RSZ": "{^}qv",
"KW-BZ": "{^}qw",
"KW-PGZ": "{^}qx",
"KW-RBGZ": "{^}qy",
"KW-PBLGSZ": "{^}qz",
"RA-Z": "{^}ra",
"R-PBZ": "{^}rb",
"R-RGZ": "{^}rc",
"R-LGZ": "{^}rd",
"R-EZ": "{^}re",
"R-PLZ": "{^}rf",
"R-PBLGZ": "{^}rg",
"R-FZ": "{^}rh",
"R-EUZ": "{^}ri",
"R-RBGSZ": "{^}rj",
"R-GZ": "{^}rk",
"R-FRZ": "{^}rl",
"R-FPZ": "{^}rm",
"R-FPLZ": "{^}rn",
"RO-Z": "{^}ro",
"R-PZ": "{^}rp",
"R-BGZ": "{^}rq",
"R-RZ": "{^}rr",
"R-SZ": "{^}rs",
"R-LZ": "{^}rt",
"R-UZ": "{^}ru",
"R-RSZ": "{^}rv",
"R-BZ": "{^}rw",
"R-PGZ": "{^}rx",
"R-RBGZ": "{^}ry",
"R-PBLGSZ": "{^}rz",
"SA-Z": "{^}sa",
"S-PBZ": "{^}sb",
"S-RGZ": "{^}sc",
"S-LGZ": "{^}sd",
"S-EZ": "{^}se",
"S-PLZ": "{^}sf",
"S-PBLGZ": "{^}sg",
"S-FZ": "{^}sh",
"S-EUZ": "{^}si",
"S-RBGSZ": "{^}sj",
"S-GZ": "{^}sk",
"S-FRZ": "{^}sl",
"S-FPZ": "{^}sm",
"S-FPLZ": "{^}sn",
"SO-Z": "{^}so",
"S-PZ": "{^}sp",
"S-BGZ": "{^}sq",
"S-RZ": "{^}sr",
"S-SZ": "{^}ss",
"S-LZ": "{^}st",
"S-UZ": "{^}su",
"S-RSZ": "{^}sv",
"S-BZ": "{^}sw",
"S-PGZ": "{^}sx",
"S-RBGZ": "{^}sy",
"S-PBLGSZ": "{^}sz",
"TA-Z": "{^}ta",
"T-PBZ": "{^}tb",
"T-RGZ": "{^}tc",
"T-LGZ": "{^}td",
"T-EZ": "{^}te",
"T-PLZ": "{^}tf",
"T-PBLGZ": "{^}tg",
"T-FZ": "{^}th",
"T-EUZ": "{^}ti",
"T-RBGSZ": "{^}tj",
"T-GZ": "{^}tk",
"T-FRZ": "{^}tl",
"T-FPZ": "{^}tm",
"T-FPLZ": "{^}tn",
"TO-Z": "{^}to",
"T-PZ": "{^}tp",
"T-BGZ": "{^}tq",
"T-RZ": "{^}tr",
"T-SZ": "{^}ts",
"T-LZ": "{^}tt",
"T-UZ": "{^}tu",
"T-RSZ": "{^}tv",
"T-BZ": "{^}tw",
"T-PGZ": "{^}tx",
"T-RBGZ": "{^}ty",
"T-PBLGSZ": "{^}tz",
"UPBZ": "{^}ub",
"URGZ": "{^}uc",
"ULGZ": "{^}ud",
"UPLZ": "{^}uf",
"UPBLGZ": "{^}ug",
"UFZ": "{^}uh",
"UEUZ": "{^}ui",
"URBGSZ": "{^}uj",
"UGZ": "{^}uk",
"UFRZ": "{^}ul",
"UFPZ": "{^}um",
"UFPLZ": "{^}un",
"UPZ": "{^}up",
"UBGZ": "{^}uq",
"URZ": "{^}ur",
"USZ": "{^}us",
"ULZ": "{^}ut",
"UUZ": "{^}uu",
"URSZ": "{^}uv",
"UBZ": "{^}uw",
"UPGZ": "{^}ux",
"URBGZ": "{^}uy",
"UPBLGSZ": "{^}uz",
"SRA-Z": "{^}va",
"SR-PBZ": "{^}vb",
"SR-RGZ": "{^}vc",
"SR-LGZ": "{^}vd",
"SR-EZ": "{^}ve",
"SR-PLZ": "{^}vf",
"SR-PBLGZ": "{^}vg",
"SR-FZ": "{^}vh",
"SR-EUZ": "{^}vi",
"SR-RBGSZ": "{^}vj",
"SR-GZ": "{^}vk",
"SR-FRZ": "{^}vl",
"SR-FPZ": "{^}vm",
"SR-FPLZ": "{^}vn",
"SRO-Z": "{^}vo",
"SR-PZ": "{^}vp",
"SR-BGZ": "{^}vq",
"SR-RZ": "{^}vr",
"SR-SZ": "{^}vs",
"SR-LZ": "{^}vt",
"SR-UZ": "{^}vu",
"SR-RSZ": "{^}vv",
"SR-BZ": "{^}vw",
"SR-PGZ": "{^}vx",
"SR-RBGZ": "{^}vy",
"SR-PBLGSZ": "{^}vz",
"WA-Z": "{^}wa",
"W-PBZ": "{^}wb",
"W-RGZ": "{^}wc",
"W-LGZ": "{^}wd",
"W-EZ": "{^}we",
"W-PLZ": "{^}wf",
"W-PBLGZ": "{^}wg",
"W-FZ": "{^}wh",
"W-EUZ": "{^}wi",
"W-RBGSZ": "{^}wj",
"W-GZ": "{^}wk",
"W-FRZ": "{^}wl",
"W-FPZ": "{^}wm",
"W-FPLZ": "{^}wn",
"WO-Z": "{^}wo",
"W-PZ": "{^}wp",
"W-BGZ": "{^}wq",
"W-RZ": "{^}wr",
"W-SZ": "{^}ws",
"W-LZ": "{^}wt",
"W-UZ": "{^}wu",
"W-RSZ": "{^}wv",
"W-BZ": "{^}ww",
"W-PGZ": "{^}wx",
"W-RBGZ": "{^}wy",
"W-PBLGSZ": "{^}wz",
"KPA-Z": "{^}xa",
"KP-PBZ": "{^}xb",
"KP-RGZ": "{^}xc",
"KP-LGZ": "{^}xd",
"KP-EZ": "{^}xe",
"KP-PLZ": "{^}xf",
"KP-PBLGZ": "{^}xg",
"KP-FZ": "{^}xh",
"KP-EUZ": "{^}xi",
"KP-RBGSZ": "{^}xj",
"KP-GZ": "{^}xk",
"KP-FRZ": "{^}xl",
"KP-FPZ": "{^}xm",
"KP-FPLZ": "{^}xn",
"KPO-Z": "{^}xo",
"KP-PZ": "{^}xp",
"KP-BGZ": "{^}xq",
"KP-RZ": "{^}xr",
"KP-SZ": "{^}xs",
"KP-LZ": "{^}xt",
"KP-UZ": "{^}xu",
"KP-RSZ": "{^}xv",
"KP-BZ": "{^}xw",
"KP-PGZ": "{^}xx",
"KP-RBGZ": "{^}xy",
"KP-PBLGSZ": "{^}xz",
"KWRA-Z": "{^}ya",
"KWR-PBZ": "{^}yb",
"KWR-RGZ": "{^}yc",
"KWR-LGZ": "{^}yd",
"KWR-EZ": "{^}ye",
"KWR-PLZ": "{^}yf",
"KWR-PBLGZ": "{^}yg",
"KWR-FZ": "{^}yh",
"KWR-EUZ": "{^}yi",
"KWR-RBGSZ": "{^}yj",
"KWR-GZ": "{^}yk",
"KWR-FRZ": "{^}yl",
"KWR-FPZ": "{^}ym",
"KWR-FPLZ": "{^}yn",
"KWRO-Z": "{^}yo",
"KWR-PZ": "{^}yp",
"KWR-BGZ": "{^}yq",
"KWR-RZ": "{^}yr",
"KWR-SZ": "{^}ys",
"KWR-LZ": "{^}yt",
"KWR-UZ": "{^}yu",
"KWR-RSZ": "{^}yv",
"KWR-BZ": "{^}yw",
"KWR-PGZ": "{^}yx",
"KWR-RBGZ": "{^}yy",
"KWR-PBLGSZ": "{^}yz",
"STKPWA-Z": "{^}za",
"STKPW-PBZ": "{^}zb",
"STKPW-RGZ": "{^}zc",
"STKPW-LGZ": "{^}zd",
"STKPW-EZ": "{^}ze",
"STKPW-PLZ": "{^}zf",
"STKPW-PBLGZ": "{^}zg",
"STKPW-FZ": "{^}zh",
"STKPW-EUZ": "{^}zi",
"STKPW-RBGSZ": "{^}zj",
"STKPW-GZ": "{^}zk",
"STKPW-FRZ": "{^}zl",
"STKPW-FPZ": "{^}zm",
"STKPW-FPLZ": "{^}zn",
"STKPWO-Z": "{^}zo",
"STKPW-PZ": "{^}zp",
"STKPW-BGZ": "{^}zq",
"STKPW-RZ": "{^}zr",
"STKPW-SZ": "{^}zs",
"STKPW-LZ": "{^}zt",
"STKPW-UZ": "{^}zu",
"STKPW-RSZ": "{^}zv",
"STKPW-BZ": "{^}zw",
"STKPW-PGZ": "{^}zx",
"STKPW-RBGZ": "{^}zy",
"STKPW-PBLGSZ": "{^}zz",
#+END_SRC
* Plover meta commands
** capitalization

   Capitalize the next word.
#+BEGIN_SRC js
"KPA": "{MODE:RESET}{-|}",
#+END_SRC

Capitalize the next word and join it to the end of the current word (suppress automatic spacing).
#+BEGIN_SRC js
"KPA*": "{MODE:RESET}{^}{-|}",
#+END_SRC

Retroactively capitalize the last word.
#+BEGIN_SRC js
"KPA-D": "{MODE:RESET}{*-|}",
#+END_SRC

Make the next word all uppercase/lowercase.
#+BEGIN_SRC js
"HRO*ER": "{>}",
#+END_SRC

** dictionary lookup
  Open up Plover's handy reverse dictionary lookup dialog, where one can type (fingerspell) any word and see what steno chords generate that word.
#+BEGIN_SRC js
"TKHRUP": "{PLOVER:LOOKUP}",
#+END_SRC
** Plover modes (e.g. all-caps)
#+BEGIN_SRC js
"TK*PL": "{MODE:RESET}",
"R*PL": "{MODE:RESET}",
"P*PL": "{MODE:LOWER}{MODE:SET_SPACE:}",
"HR*PL": "{MODE:LOWER}{MODE:SET_SPACE: }",
"KR*PL": "{MODE:CAPS}{MODE:SET_SPACE:_}",
#+END_SRC
** spacing

   Retroactively lowercase/uppercase.
#+BEGIN_SRC js
"-FRD": "{MODE:RESET}{*>}",
"-RGD": "{MODE:RESET}{*<}",
#+END_SRC

Retroactively insert a space before the last word.
#+BEGIN_SRC js
"-FPD": "{MODE:RESET}{*?}",
"S-PD": "{MODE:RESET}{*?}",
#+END_SRC

Retroactively delete a space before the last word.
#+BEGIN_SRC js
"TK-FPD": "{*!}",
#+END_SRC

Attach the next word to the end of the current word.
#+BEGIN_SRC js
"SKHR-PB": "{^};",
#+END_SRC

* uncategorized
#+BEGIN_SRC js
"*T": "{*}",
"*FP": "{#space}",
"UFP": "{^}_{^}",
"TK-FP": "{^}",
"SPWR-TS": ">>",
"SPWR-S": ">>",
"KWA*L": "{^=^}",
"KWA*LS": "{^ = ^}",
"T-B": "{#tab}",
"T-PB": "{#shift(tab)}",
"TP-B": "{#shift(tab)}",
"STPH-T": "{#page_up}",
"STPH-S": "{#page_down}",
"*F": "{#page_up}",
"*R": "{#page_down}",
"*P": "{#home}",
"STPH-F": "{#home}",
"*L": "{#end}",
"STPH-L": "{#end}",
"KWH-EU": "{^ciw}{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KWH-A": "{^caw}{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KH-EUFR": "{^ci(}{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KH-AFR": "{^ca(}{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KH-EUGS": "{^ci\"}{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KH-AGS": "{^ca\"}{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"R*EU": "i{MODE:RESET}{^}",
"HR*EU": "i{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KR*EU": "i{MODE:CAPS}{MODE:SET_SPACE:_}{^}",
"RA*": "a{MODE:RESET}{^}",
"PA*": "a{MODE:LOWER}{MODE:SET_SPACE:}{^}",
"HRA*": "a{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KRA*": "a{MODE:CAPS}{MODE:SET_SPACE:_}{^}",
"RO*": "o{MODE:RESET}{^}",
"PO*": "o{MODE:LOWER}{MODE:SET_SPACE:}{^}",
"HRO*": "o{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KRO*": "o{MODE:CAPS}{MODE:SET_SPACE:_}{^}",
"RO*P": "{MODE:RESET}{MODE:SET_SPACE:}O{MODE:RESET}{^}",
"PO*P": "{MODE:RESET}{MODE:SET_SPACE:}O{MODE:LOWER}{MODE:SET_SPACE:}{^}",
"HRO*P": "{MODE:RESET}{MODE:SET_SPACE:}O{MODE:LOWER}{MODE:SET_SPACE: }{^}",
"KRO*P": "{MODE:RESET}{MODE:SET_SPACE:}O{MODE:CAPS}{MODE:SET_SPACE:_}{^}",
"SKWR-L": "{#space j l}",
"SPA-Z": "{^}{#space a}",
"SP-PBZ": "{^}{#space b}",
"SP-RGZ": "{^}{#space c}",
"SP-LGZ": "{^}{#space d}",
"SP-EZ": "{^}{#space e}",
"SP-PLZ": "{^}{#space f}",
"SP-PBLGZ": "{^}{#space g}",
"SP-FZ": "{^}{#space h}",
"SP-EUZ": "{^}{#space i}",
"SP-RBGSZ": "{^}{#space j}",
"SP-GZ": "{^}{#space k}",
"SP-FRZ": "{^}{#space l}",
"SP-FPZ": "{^}{#space m}",
"SP-FPLZ": "{^}{#space n}",
"SPO-Z": "{^}{#space o}",
"SP-PZ": "{^}{#space p}",
"SP-BGZ": "{^}{#space q}",
"SP-RZ": "{^}{#space r}",
"SP-SZ": "{^}{#space s}",
"SP-LZ": "{^}{#space t}",
"SP-UZ": "{^}{#space u}",
"SP-RSZ": "{^}{#space v}",
"SP-BZ": "{^}{#space w}",
"SP-PGZ": "{^}{#space x}",
"SP-RBGZ": "{^}{#space y}",
"SP-PBLGSZ": "{^}{#space z}",
#+END_SRC
* vim
This section provides chords for jumping up or down a given number of lines in vim.

To jump by a certain number of lines, fingerspell the number as usual, but append the D/Z key to the chord to indicate up/down.

NOTE: The Plover dictionary format has the quirk that chords can not specified using the number key ("#"). For example, the chord "#S-Z" must be written as "1-Z" instead.

#+BEGIN_SRC js
"1-Z": "{^}1j",
"2-Z": "{^}2j",
"3-Z": "{^}3j",
"4-Z": "{^}4j",
"5-Z": "{^}5j",
"-6Z": "{^}6j",
"-7Z": "{^}7j",
"-8Z": "{^}8j",
"-9Z": "{^}9j",
"10-Z": "{^}10j",
"1*Z": "{^}11j",
"12-Z": "{^}12j",
"13-Z": "{^}13j",
"14-Z": "{^}14j",
"15-Z": "{^}15j",
"1-6Z": "{^}16j",
"1-7Z": "{^}17j",
"1-8Z": "{^}18j",
"1-9Z": "{^}19j",
"20-Z": "{^}20j",
"12-EUZ": "{^}21j",
"2*Z": "{^}22j",
"22-Z": "{^}22j",
"23-Z": "{^}23j",
"24-Z": "{^}24j",
"25-Z": "{^}25j",
"2-6Z": "{^}26j",
"2-7Z": "{^}27j",
"2-8Z": "{^}28j",
"2-9Z": "{^}29j",
"30-Z": "{^}30j",
"13-EUZ": "{^}31j",
"23-EUZ": "{^}32j",
"3*Z": "{^}33j",
"34-Z": "{^}34j",
"35-Z": "{^}35j",
"3-6Z": "{^}36j",
"3-7Z": "{^}37j",
"3-8Z": "{^}38j",
"3-9Z": "{^}39j",
"1-D": "{^}1k",
"2-D": "{^}2k",
"3-D": "{^}3k",
"4-D": "{^}4k",
"5-D": "{^}5k",
"-6D": "{^}6k",
"-7D": "{^}7k",
"-8D": "{^}8k",
"-9D": "{^}9k",
"10-D": "{^}10k",
"1*D": "{^}11k",
"12-D": "{^}12k",
"13-D": "{^}13k",
"14-D": "{^}14k",
"15-D": "{^}15k",
"1-6D": "{^}16k",
"1-7D": "{^}17k",
"1-8D": "{^}18k",
"1-9D": "{^}19k",
"20-D": "{^}20k",
"12-EUD": "{^}21k",
"2*D": "{^}22k",
"23-D": "{^}23k",
"24-D": "{^}24k",
"25-D": "{^}25k",
"2-6D": "{^}26k",
"2-7D": "{^}27k",
"2-8D": "{^}28k",
"2-9D": "{^}29k",
"30-D": "{^}30k",
"13-EUD": "{^}31k",
"23-EUD": "{^}32k",
"3*D": "{^}33k",
"34-D": "{^}34k",
"35-D": "{^}35k",
"3-6D": "{^}36k",
"3-7D": "{^}37k",
"3-8D": "{^}38k",
"3-9D": "{^}39k"
#+END_SRC

* end dictionary
#+BEGIN_SRC js
}
#+END_SRC
