#+TITLE: A Coder's Plover Dictionary
#+PROPERTY: header-args :tangle user.json

* about this config
I am a heavy user of emacs, vim, and the linux command line. When it comes to coding, the main challenge I have experienced with Plover is the automatic spacing and capitalization. While automatic spacing and capitalization is a big part of what makes stenography so efficient when typing natural language, it can wreak havoc in other contexts. For example, the unexpected insertion of spaces can interfere with the composition of normal mode commands in vim (e.g. "d3j" to delete the current line and the 3 lines below it). For this reason, I have overridden the default fingerspelling behavior to always attach the new letter/number to the end of the current word.

Another challenge is that there is no auto-repeat when holding down keys on a steno machine. This prevents you from holding down "j" and "k" to scroll up and down in vim, for example. You might be surprised how often you use this functionality, even if you are a seasoned vimmer. While I'm still working on it, I'm attempting to overcome this issue by using a combination of =relativenumber= and numeric arguments before j/k.
* start dictionary
#+BEGIN_SRC js
{
#+END_SRC
* shared python code
#+NAME: fingerspelling
#+BEGIN_SRC python :tangle no :results output silent
# fingerspelling chords for the left hand

left_consonants = {}
left_consonants['b'] = "PW"
left_consonants['c'] = "KR"
left_consonants['d'] = "TK"
left_consonants['f'] = "TP"
left_consonants['g'] = "TKPW"
left_consonants['h'] = "H"
left_consonants['j'] = "SKWR"
left_consonants['k'] = "K"
left_consonants['l'] = "HR"
left_consonants['m'] = "PH"
left_consonants['n'] = "TPH"
left_consonants['p'] = "P"
left_consonants['q'] = "KW"
left_consonants['r'] = "R"
left_consonants['s'] = "S"
left_consonants['t'] = "T"
left_consonants['v'] = "SR"
left_consonants['w'] = "W"
left_consonants['x'] = "KP"
left_consonants['y'] = "KWR"
left_consonants['z'] = "STKPW"

left_vowels = {}
left_vowels['a'] = "A"
left_vowels['o'] = "O"

left_chars = left_consonants.copy()
left_chars.update(left_vowels)

# fingerspelling chords for the right hand

right_consonants = {}
right_consonants['b'] = "PB"
right_consonants['c'] = "RG"
right_consonants['d'] = "LG"
right_consonants['f'] = "PL"
right_consonants['g'] = "PBLG"
right_consonants['h'] = "F"
right_consonants['j'] = "RBGS"
right_consonants['k'] = "G"
right_consonants['l'] = "FR"
right_consonants['m'] = "FP"
right_consonants['n'] = "FPL"
right_consonants['p'] = "P"
right_consonants['q'] = "BG"
right_consonants['r'] = "R"
right_consonants['s'] = "S"
right_consonants['t'] = "L"
right_consonants['v'] = "RS"
right_consonants['w'] = "B"
right_consonants['x'] = "PG"
right_consonants['y'] = "RBG"
right_consonants['z'] = "PBLGS"

right_vowels = {}
right_vowels['e'] = "E"
right_vowels['i'] = "EU"
right_vowels['u'] = "U"

right_chars = right_consonants.copy()
right_chars.update(right_vowels)

# all standard fingerspelling chords
# (left-hand consonants/vowels plus right-hand vowels)

fingerspelling_chars = left_chars.copy()
fingerspelling_chars.update(right_vowels)
#+END_SRC

* bioinformatics
#+BEGIN_SRC js
"PW-EUS": "abyss",
"PW*EUS": "ABySS",
"ARBGS": "arcs",
"A*RBGS": "arks",
"PWRO-EUPB": "Bruijn",
"PW-LT": "btl",
"PW*LT": "BTL",
"KOPB/TEUG": "contig",
"KOPB/TEUGS": "contigs",
"TKPW-PBLG": "de Bruijn graph",
"TKPW*PBLG": "dbg",
"TKPW-G": "de Bruijn graph",
"TKPW*G": "dbg",
"TKEUFT": "dist",
"EPL": "emc",
"HRAO-UPL/TPHA": "Illumina",
"EUL/HRAO-UPL/TPHA": "Illumina",
"KPH-ER": "k-mer",
"KPH-ERS": "k-mers",
"KPH*ER": "kmer",
"KPH*ERS": "kmers",
"K-ERBGT": "konnector",
"K*ERBGT": "Konnector",
"PH-EUP": "mpi",
"PH*EUP": "MPI",
"PRAG": "pragma",
"KWAFT": "quast",
"KWAUFT": "quast",
"SAO*EBG": "seq",
"SEUT/KA": "Sitka",
"TEUG/PHEUPBT": "Tigmint",
"AOUPB/TEUG": "unitig",
"AOUPB/TEUGS": "unitigs",
#+END_SRC
* brackets
#+BEGIN_SRC js
"HR-RPB": "{^}({^}",
"PW-RPB": "{^}[{^}",
"TK-RPB": "{^}\\{{^}",
"S-RPB":  "{^}<",
"S-RPBS":  "<<",
"PWR-FR": "{^})",
"PWR-PB": "{^}]",
"PWR-LG": "{^}\\}",
"PWR-TS": "{^}>",
"PWR-S": "{^}>",
#+END_SRC
* coding
** C/C++ keywords
#+BEGIN_SRC js
"KHR-PBS": "{^}::{^}",
"KRER": "cerr",
"KROUT": "cout",
"KOPBTS": "const",
"ST-D": "std{^}",
"STRUBGT": "struct",
"TAOEUP/TKEF": "typedef",
"TAOEUP/TPHAEUPL": "typename",
#+END_SRC
** expressions/assignment

#+BEGIN_SRC js
"KWA*L": "{MODE:RESET}{^=^}{MODE:LOWER}{MODE:SET_SPACE:}",
"KWA*LS": "{MODE:RESET}{^ = ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"KW*LT": "{MODE:RESET}{^ == ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"TPH*E": "{MODE:RESET}{^ != ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"K*PL": "{MODE:RESET}{^, ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"KR*PL": "{MODE:RESET}{^, ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"HR*T": "{MODE:RESET}{^ < ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"HR*ET": "{MODE:RESET}{^ <= ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"TKPW*T": "{MODE:RESET}{^ > ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"TKPW*ET": "{MODE:RESET}{^ >= ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"HR*PBD": "{MODE:RESET}{^ && ^}{MODE:LOWER}{MODE:SET_SPACE:}",
"HRO*R": "{MODE:RESET}{^ || ^}{MODE:LOWER}{MODE:SET_SPACE:}",
#+END_SRC
* command-line
** shell commands
#+BEGIN_SRC js
"POEUP": "{MODE:RESET}{MODE:LOWER}../{^}",
"POEU": "{MODE:RESET}{MODE:LOWER}./{^}",
"OEUP": "{MODE:RESET}{MODE:LOWER}./{^}",
"TKR-": "cd{MODE:RESET}{MODE:LOWER}",
"KR-D": "cd{MODE:RESET}{MODE:LOWER}",
"KR-PL": "chmod{MODE:RESET}{MODE:LOWER}",
"KHR-PL": "chmod{MODE:RESET}{MODE:LOWER}",
"KR-PLD": "chmod{MODE:RESET}{MODE:LOWER}",
"KHR-PLD": "chmod{MODE:RESET}{MODE:LOWER}",
"KR-P": "cp{MODE:RESET}{MODE:LOWER}",
"SKWRAO-ER/RA": "jira",
"SKWRAO*ER/RA": "JIRA",
"SKWRA*EUFPB": "json",
"HR-S": "ls{MODE:RESET}{MODE:LOWER}",
"HR-PB": "ln{MODE:RESET}{MODE:LOWER}",
"PH-D": "mkdir{MODE:RESET}{MODE:LOWER}",
"PH-F": "mv{MODE:RESET}{MODE:LOWER}",
"O*RG": "org",
"PW-D": "pwd{MODE:RESET}{MODE:LOWER}",
"R-PL": "rm{MODE:RESET}{MODE:LOWER}",
"R-D": "rmdir{MODE:RESET}{MODE:LOWER}",
"SH": "ssh{MODE:RESET}{MODE:LOWER}",
"TPHUBGS": "tmux{MODE:RESET}{MODE:LOWER}",
"KPARGS": "xargs{MODE:RESET}{MODE:LOWER}",
"PAO*EUP": "{MODE:RESET}{MODE:LOWER}{^ | ^}",
#+END_SRC
** command-line switches
#+BEGIN_SRC js
"TK-RB": "{MODE:RESET}{MODE:LOWER}--{^}",
#+END_SRC

#+NAME: command-line-switches
#+BEGIN_SRC python :noweb yes :tangle no :results output silent

<<fingerspelling>>

for char, chord in fingerspelling_chars.iteritems():
        print('"{}-{}": "{}",'.format(chord, "RBG", char))
        print('"{}-{}": "{}",'.format(chord, "RPBG", char.upper()))
#+END_SRC

#+BEGIN_SRC js :noweb tangle
<<command-line-switches()>>
#+END_SRC
* emojis
#+BEGIN_SRC js
"AO-E/PHO-EPBLG": "emoji",
"SPHAO*EUL": ":-)",
#+END_SRC
* fingerspelling
In this section, we override the default behavior of fingerspelling to attach all fingerspelled letters/symbols/numbers to the end of the current word. This prevents Plover's automatic spacing from interfering with the typing of normal mode commands in vim.
** symbol chars (e.g. !, @, #)
Assign these to the number keys, similar to a normal keyboard, using the star key ("*") as the modifier.
#+BEGIN_SRC js
"0*": "{^})",
"1*": "{^}!",
"2*": "{^}@",
"3*": "{^}#",
"4*": "{^}$",
"5*": "{^}%",
"*6": "{^}^",
"*7": "{^}&",
"*8": "{^}*",
"*9": "{^}(",
#+END_SRC
* pass-through keys
** Enter key
#+BEGIN_SRC js
"TR-Z": "{# return}",
#+END_SRC
** Escape key
#+BEGIN_SRC js
"#": "{#escape}",
"SK-Z": "{#escape}",
"SKP-Z": "{#escape}",
#+END_SRC
** function keys
 To type a function key (e.g. F1), hold down -PL and fingerspell the number with the left hand. The mnemonic for -PL is that it is the mirror image for fingerspelling "F" with the left hand.
 #+BEGIN_SRC js
"178": "{#F1}",
"278": "{#F2}",
"378": "{#F3}",
"478": "{#F4}",
"578": "{#F5}",
"678": "{#F6}",
"778": "{#F7}",
"878": "{#F8}",
"978": "{#F9}",
"1078": "{#F10}",
"1278": "{#F12}",
 #+END_SRC

** letters
#+NAME: pass-through-letters
#+BEGIN_SRC python :noweb yes :tangle no :results output silent

<<fingerspelling>>

for char, chord in fingerspelling_chars.iteritems():
        print('"{}-Z": "{{# {}}}",'.format(chord, char))
        print('"{}*Z": "{{# shift({})}}",'.format(chord, char))
#+END_SRC

#+BEGIN_SRC js :noweb tangle
<<pass-through-letters()>>
#+END_SRC

** modifier keys (alt/control/shift/win)
*** alt
 #+BEGIN_SRC js
"KHR*FPB": "{#alt(shift(colon))}",
"P*FP": "{#alt(period)}",
"S*FP": "{#alt(space)}",
"SH*P": "{#alt(space)}",
"HO*EU": "{#alt(slash)}",
"O*EUF": "{#alt(slash)}",
"T*FB": "{#alt(tab)}",
"TH*B": "{#alt(tab)}",
"A*F": "{#alt(a)}",
"PW*F": "{#alt(b)}",
"KR*F": "{#alt(c)}",
"TK*F": "{#alt(d)}",
"*EF": "{#alt(e)}",
"H*E": "{#alt(e)}",
"TP*F": "{#alt(f)}",
"TKPW*F": "{#alt(g)}",
"H*F": "{#alt(h)}",
"*EUF": "{#alt(i)}",
"H*EU": "{#alt(i)}",
"SKWR*F": "{#alt(j)}",
"K*F": "{#alt(k)}",
"HR*F": "{#alt(l)}",
"PH*F": "{#alt(m)}",
"TPH*F": "{#alt(n)}",
"O*F": "{#alt(o)}",
"P*F": "{#alt(p)}",
"KW*F": "{#alt(q)}",
"R*F": "{#alt(r)}",
"S*F": "{#alt(s)}",
"T*F": "{#alt(t)}",
"*UF": "{#alt(u)}",
"W*U": "{#alt(u)}",
"SR*F": "{#alt(v)}",
"W*F": "{#alt(w)}",
"KP*F": "{#alt(x)}",
"KWR*F": "{#alt(y)}",
"STKPW*F": "{#alt(z)}",
 #+END_SRC
*** control
 #+BEGIN_SRC js
"0*R": "{#control(0)}",
"1*R": "{#control(1)}",
"2*R": "{#control(2)}",
"3*R": "{#control(3)}",
"4*R": "{#control(4)}",
"5*R": "{#control(5)}",
"R*6": "{#control(6)}",
"R*7": "{#control(7)}",
"R*8": "{#control(8)}",
"R*9": "{#control(9)}",
"HR*RPB": "{#control(parenleft)}",
"PW*RPB": "{#control(bracketleft)}",
"TK*RPB": "{#control(braceleft)}",
"PWR*FR": "{#control(parenright)}",
"PWR*PB": "{#control(bracketright)}",
"PWR*LG": "{#control(braceright)}",
"KHR-R": "{#control(left)}",
"KHR-G": "{#control(right)}",
"KHR-P": "{#control(up)}",
"KHR-B": "{#control(down)}",
"R*EUPBS": "{#control(insert)}",
"R*T": "{#control(shift(plus))}",
"R*S": "{#control(minus)}",
"RO*EU": "{#control(slash)}",
"O*EUR": "{#control(slash)}",
"S*RP": "{#control(space)}",
"T*RB": "{#control(tab)}",
"TR*B": "{#control(tab)}",
"A*R": "{#control(a)}",
"PW*R": "{#control(b)}",
"KR*R": "{#control(c)}",
"TK*R": "{#control(d)}",
"R*E": "{#control(e)}",
"TP*R": "{#control(f)}",
"TKPW*R": "{#control(g)}",
"H*R": "{#control(h)}",
"*EUR": "{#control(i)}",
"R*EU": "{#control(i)}",
"SKWR*R": "{#control(j)}",
"K*R": "{#control(k)}",
"HR*R": "{#control(l)}",
"PH*R": "{#control(m)}",
"TPH*R": "{#control(n)}",
"O*R": "{#control(o)}",
"P*R": "{#control(p)}",
"KW*R": "{#control(q)}",
"R*R": "{#control(r)}",
"S*R": "{#control(s)}",
"T*R": "{#control(t)}",
"*UR": "{#control(u)}",
"R*U": "{#control(u)}",
"SR*R": "{#control(v)}",
"W*R": "{#control(w)}",
"KP*R": "{#control(x)}",
"KWR*R": "{#control(y)}",
"STKPW*R": "{#control(z)}",
 #+END_SRC
*** shift
 #+BEGIN_SRC js
"SH*EUPBS": "{#shift(insert)}",
"SH*P": "{#shift(up)}",
"SH*B": "{#shift(down)}",
"SH*R": "{#shift(left)}",
"SH*G": "{#shift(right)}",
"SH*RB": "{#shift(control(left))}",
"SH*BG": "{#shift(control(right))}",
"ST*B": "{#shift(tab)}",
"T*BS": "{#shift(tab)}",
 #+END_SRC
*** shift+win
 Same as the Windows key chords, but with the S key appended at the end.
 #+BEGIN_SRC js
"A*PBS": "{#windows(shift(a))}",
"PW*PBS": "{#windows(shift(b))}",
"KR*PBS": "{#windows(shift(c))}",
"TK*PBS": "{#windows(shift(d))}",
"*EPBS": "{#windows(shift(e))}",
"TP*PBS": "{#windows(shift(f))}",
"TKPW*PBS": "{#windows(shift(g))}",
"H*PBS": "{#windows(shift(h))}",
"*EUPBS": "{#windows(shift(i))}",
"SKWR*PBS": "{#windows(shift(j))}",
"K*PBS": "{#windows(shift(k))}",
"HR*PBS": "{#windows(shift(l))}",
"PH*PBS": "{#windows(shift(m))}",
"TPH*PBS": "{#windows(shift(n))}",
"O*PBS": "{#windows(shift(o))}",
"P*PBS": "{#windows(shift(p))}",
"KW*PBS": "{#windows(shift(q))}",
"R*PBS": "{#windows(shift(r))}",
"S*PBS": "{#windows(shift(s))}",
"T*PBS": "{#windows(shift(t))}",
"*UPBS": "{#windows(shift(u))}",
"SR*PBS": "{#windows(shift(v))}",
"W*PBS": "{#windows(shift(w))}",
"KP*PBS": "{#windows(shift(x))}",
"KWR*PBS": "{#windows(shift(y))}",
"STKPW*PBS": "{#windows(shift(z))}",
 #+END_SRC
*** win
 #+BEGIN_SRC js
"*PB": "{#windows}",
"R*RPB": "{#windows(return)}",
"PWR*R": "{#windows(return)}",
"P*LG": "{#windows(up)}",
"K*LG": "{#windows(left)}",
"W*LG": "{#windows(down)}",
"R*LG": "{#windows(right)}",
"A*PB": "{#windows(a)}",
"PW*PB": "{#windows(b)}",
"KR*PB": "{#windows(c)}",
"TK*PB": "{#windows(d)}",
"*EPB": "{#windows(e)}",
"TP*PB": "{#windows(f)}",
"TKPW*PB": "{#windows(g)}",
"H*PB": "{#windows(h)}",
"*EUPB": "{#windows(i)}",
"SKWR*PB": "{#windows(j)}",
"K*PB": "{#windows(k)}",
"HR*PB": "{#windows(l)}",
"PH*PB": "{#windows(m)}",
"TPH*PB": "{#windows(n)}",
"O*PB": "{#windows(o)}",
"P*PB": "{#windows(p)}",
"KW*PB": "{#windows(q)}",
"R*PB": "{#windows(r)}",
"S*PB": "{#windows(s)}",
"T*PB": "{#windows(t)}",
"*UPB": "{#windows(u)}",
"SR*PB": "{#windows(v)}",
"W*PB": "{#windows(w)}",
"KP*PB": "{#windows(x)}",
"KWR*PB": "{#windows(y)}",
"STKPW*PB": "{#windows(z)}",
 #+END_SRC
** numbers
#+NAME: pass-through-numbers
#+BEGIN_SRC python :tangle no :results output silent
for i in xrange(1, 99):
    if i <= 9:
            print('"{}Z": "{{#{}}}",'.format(i,i))
    else:
            digit1 = i // 10
            digit2 = i % 10
            swap_keys = ''
            if digit1 > digit2 and digit2 > 0:
                    digit1, digit2 = digit2, digit1
                    swap_keys = 'EU'
            if digit1 <= 5 and digit2 <= 5:
                    chord = '{}{}-{}'.format(digit1, digit2, swap_keys)
            if digit1 <= 5 and digit2 > 5:
                    chord = '{}-{}{}'.format(digit1, swap_keys, digit2)
            if digit1 > 5 and digit2 > 5:
                    chord = '-{}{}{}'.format(swap_keys, digit1, digit2)
            print('"{}Z": "{{#{}}}",'.format(chord, i))
#+END_SRC

#+BEGIN_SRC js :noweb tangle
<<pass-through-numbers()>>
#+END_SRC
** Space
#+BEGIN_SRC js
"SP-Z": "{# space}",
#+END_SRC
** symbol chars (e.g. !, @, #)
Assign these to the number keys, similar to a normal keyboard, using the star key ("*") as the modifier.
#+BEGIN_SRC js
"0*Z": "{# parenright}",
"1*Z": "{# exclam}",
"2*Z": "{# at}",
"3*Z": "{# numbersign}",
"4*Z": "{# dollar}",
"5*Z": "{# percent}",
"*6Z": "{# asciicircum}",
"*7Z": "{# ampersand}",
"*8Z": "{# asterisk}",
"*9Z": "{# parenleft}",
#+END_SRC
** digrams

I find the ability to fingerspell digrams (two-letter combinations) to be very handy. For example, I have used various vim plugins for Firefox/Chrome (e.g. Vimperator, Vimium, VimFX, tridactyl) that allow keyboard navigation of hyperlinks by labeling the links with two-letter "hints".

The idea behind these chords is to fingerspell the first letter with the left hand as usual, and to use the right hand to fingerspell the second letter. The chords for fingerspelling with the right hand are the mirror image of the chords for the left hand. For example, the right hand chord for "m" is -FP. Finally, all digram chords end with the Z key.

#+NAME: pass-through-digrams
#+BEGIN_SRC python :noweb yes :tangle no :results output silent

<<fingerspelling>>

for key1, value1 in left_chars.iteritems():
    for key2, value2 in right_chars.iteritems():
        # both letters lowercase
        print('"{}-{}Z": "{{# {} {}}}",'.format(value1,value2,key1,key2))
        # first letter uppercase
        print('"{}*-{}Z": "{{# shift({}) {}}}",'.format(value1,value2,key1,key2))
        # second letter uppercase
        print('"{}-{}DZ": "{{# {} shift({})}}",'.format(value1,value2,key1,key2))
        # both letters uppercase
        print('"{}*-{}DZ": "{{# shift({}) shift({})}}",'.format(value1,value2,key1,key2))

for key1, value1 in left_consonants.iteritems():
    for key2, value2 in left_vowels.iteritems():
        # both letters lowercase
        print('"{}{}-Z": "{{# {} {}}}",'.format(value1,value2,key1,key2))
        # first letter uppercase
        print('"{}{}*Z": "{{# shift({}) {}}}",'.format(value1,value2,key1,key2))
        # second letter uppercase
        print('"{}{}-DZ": "{{# {} shift({})}}",'.format(value1,value2,key1,key2))
        # both letters uppercase
        print('"{}{}*DZ": "{{# shift({}) shift({})}}",'.format(value1,value2,key1,key2))

for key1, value1 in right_vowels.iteritems():
    for key2, value2 in right_consonants.iteritems():
        # both letters lowercase
        print('"-{}{}Z": "{{# {} {}}}",'.format(value1,value2,key1,key2))
        # first letter uppercase
        print('"*{}{}Z": "{{# shift({}) {}}}",'.format(value1,value2,key1,key2))
        # second letter uppercase
        print('"-{}{}DZ": "{{# {} shift({})}}",'.format(value1,value2,key1,key2))
        # both letters uppercase
        print('"*{}{}DZ": "{{# shift({}) shift({})}}",'.format(value1,value2,key1,key2))
#+END_SRC

#+BEGIN_SRC js :noweb tangle
<<pass-through-digrams()>>
#+END_SRC
** trigrams
Handy trigrams for vim.

#+BEGIN_SRC js
"KR-EUBZ": "{# c i w}",
"KRA-BZ": "{# c a w}",
"KR-EUBDZ": "{# c i shift(w)}",
"KRA-BDZ": "{# c a shift(w)}",
"KR-EUGSZ": "{# c i quotedbl}",
"KRA-GSZ": "{# c a quotedbl}",
"TK-EUBZ": "{# d i w}",
"TKA-BZ": "{# d a w}",
"TK-EUBDZ": "{# d i shift(w)}",
"TKA-BDZ": "{# d a shift(w)}",
"KWR-EUBZ": "{# y i w}",
"KWRA-BZ": "{# y a w}",
"KWR-EUBDZ": "{# y i shift(w)}",
"KWRA-BDZ": "{# y a shift(w)}",
#+END_SRC

* people's names
#+BEGIN_SRC js
"TPHAFRPB": "Inanc",
"REPB/AEU": "Rene",
"RUP": "Rup",
"RAOUP": "Rup",
"SHAUPB": "Shaun",
"SRA-PBD": "Vandervalk",
#+END_SRC
* Plover meta commands
** capitalization

   Capitalize the next word.
#+BEGIN_SRC js
"KPA": "{MODE:RESET}{-|}",
#+END_SRC

Capitalize the next word and join it to the end of the current word (suppress automatic spacing).
#+BEGIN_SRC js
"KPA*": "{MODE:RESET}{^}{-|}",
#+END_SRC

Retroactively capitalize the last word.
#+BEGIN_SRC js
"KPA-D": "{MODE:RESET}{*-|}",
#+END_SRC

Retroactively lowercase the last word. (Mnemonic: "U" for uncapitalize.)
#+BEGIN_SRC js
"KPA-UD": "{*>}",
#+END_SRC

Make the next word all uppercase/lowercase.
#+BEGIN_SRC js
"HRO*ER": "{>}",
#+END_SRC

Retroactively lowercase/uppercase.
#+BEGIN_SRC js
"-FRD": "{MODE:RESET}{*>}",
"-RGD": "{MODE:RESET}{*<}",
#+END_SRC

** dictionary lookup
  Open up Plover's handy reverse dictionary lookup dialog, where one can type (fingerspell) any word and see what steno chords generate that word.
#+BEGIN_SRC js
"TKHRUP": "{PLOVER:LOOKUP}",
#+END_SRC
** Plover modes (e.g. all-caps)
#+BEGIN_SRC js
"KR*PL": "{MODE:CAPS}{MODE:SET_SPACE:_}",
"TK*PL": "{MODE:RESET}",
"R*PL": "{MODE:RESET}",
"P*PL": "{MODE:LOWER}{MODE:SET_SPACE:}",
"HR*PL": "{MODE:LOWER}{MODE:SET_SPACE: }",
#+END_SRC
** spacing

Retroactively insert a space before the last word.
#+BEGIN_SRC js
"-FPD": "{MODE:RESET}{*?}",
"S-PD": "{MODE:RESET}{*?}",
#+END_SRC

Retroactively delete a space before the last word.
#+BEGIN_SRC js
"TK-FPD": "{*!}",
#+END_SRC

Attach the next word to the end of the current word.
#+BEGIN_SRC js
"T-FP": "{^}",
#+END_SRC

* uncategorized
#+BEGIN_SRC js
"*T": "{*}",
"*FP": "{#space}",
"UFP": "{^}_{^}",
"TK-FP": "{^}",
"SPWR-TS": ">>",
"SPWR-S": ">>",
"T-B": "{#tab}",
"T-PB": "{#shift(tab)}",
"TP-B": "{#shift(tab)}",
"STPH-T": "{#page_up}",
"STPH-S": "{#page_down}",
"*F": "{#page_up}",
"*R": "{#page_down}",
"*P": "{#home}",
"STPH-F": "{#home}",
"*L": "{#end}",
"STPH-L": "{#end}"
#+END_SRC

* end dictionary
#+BEGIN_SRC js
}
#+END_SRC
