;;; pgmacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pgmacs.el

(autoload 'pgmacs-open "pgmacs" "\
Browse the contents of PostgreSQL database to which we are connected over CON.

(fn CON)")
(autoload 'pgmacs-open-string "pgmacs" "\
Open PGmacs on database specified by CONNECTION-STRING.
CONNECTION-STRING is a PostgreSQL connection string of the form
`dbname=mydb user=me host=localhost password=foo'.
The supported keywords in the connection string are host,
hostaddr, port, dbname, user, password, sslmode (partial support)
and application_name.

(fn CONNECTION-STRING)" t)
(autoload 'pgmacs-open-uri "pgmacs" "\
Open PGmacs on database specified by CONNECTION-URI.
CONNECTION-URI is a PostgreSQL connection URI of the form
`postgresql://user:pass@host/dbname'.

(fn CONNECTION-URI)" t)
(autoload 'pgmacs "pgmacs" "\
Open a widget-based login buffer for PostgreSQL.
Widget fields are pre-populated by the values of the following
enviroment variables, if set:

- POSTGRES_DATABASE, POSTGRESQL_DATABASE, POSTGRES_DB, PGDATABASE
- POSTGRES_HOSTNAME, PGHOST
- POSTGRES_PORT_NUMBER, POSTGRESQL_PORT_NUMBER, PGPORT
- POSTGRES_USER, POSTGRESQL_USERNAME, PGUSER
- POSTGRES_PASSWORD, POSTGRESQL_PASSWORD, PGPASSWORD
" t)
(register-definition-prefixes "pgmacs" '("pgmacs-"))


;;; Generated autoloads from pgmacs-chrome.el

(register-definition-prefixes "pgmacs-chrome" '("pgmacs--"))


;;; Generated autoloads from pgmacs-schemaspy.el

(register-definition-prefixes "pgmacs-schemaspy" '("pgmacs-"))


;;; Generated autoloads from pgmacs-sql-keywords.el

(register-definition-prefixes "pgmacs-sql-keywords" '("pgmacs--postgresql-keywords"))


;;; Generated autoloads from pgmacstbl.el

(register-definition-prefixes "pgmacstbl" '("pgmacstbl"))

;;; End of scraped data

(provide 'pgmacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pgmacs-autoloads.el ends here
