;;; pg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pg.el

(register-definition-prefixes "pg" '("make-pgcon" "pg-" "pgcon" "with-pg-"))


;;; Generated autoloads from pg-bm25.el

(register-definition-prefixes "pg-bm25" '("pg-"))


;;; Generated autoloads from pg-geometry.el

(register-definition-prefixes "pg-geometry" '("pg-"))


;;; Generated autoloads from pg-gis.el

(register-definition-prefixes "pg-gis" '("pg-"))


;;; Generated autoloads from pg-lo.el

(register-definition-prefixes "pg-lo" '("pg-"))

;;; End of scraped data

(provide 'pg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pg-autoloads.el ends here
